import requests
import json
from confidential import api_key

#return: news: a 2D list of news articles to be later formatted as a pdf in NewsReport.py
def pull_news():
    news = []
    url = "https://rapidapi.p.rapidapi.com/news/list"

    querystring = {"id": "markets"}

    headers = {
        'x-rapidapi-host': "bloomberg-market-and-financial-news.p.rapidapi.com",
        'x-rapidapi-key': api_key
    }

    response = requests.request("GET", url, headers=headers, params=querystring)
    response = response.json()
    response = list(response.items())

    articles = response[1][1]

    for i in range(1, len(articles)):
        j = articles[i]['stories']
        if not j == []:
            for l in range(0, len(j)):
                if not j[l]['summary'] == '':
                    news.append([j[l]['title'], j[l]['summary'], j[l]['shortURL'], j[l]['abstract']])
                else:
                    news.append([j[l]['title'], j[l]['autoGeneratedSummary'], j[l]['shortURL'], j[l]['abstract']])

    return news
