# Generated by Django 3.1.1 on 2020-11-10 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_auto_20201013_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStockOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharpe_ratio', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('sortino_ratio', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('alpha', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('beta', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='date',
            new_name='date_updated',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='SharpeRatio',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='SortinoRatio',
        ),
        migrations.AddField(
            model_name='stock',
            name='sharpe_ratio',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sortino_ratio',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='userstockownership',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.stock'),
        ),
        migrations.AddField(
            model_name='userstockownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
